POST http://localhost:8080/animal
Content-Type: application/json

{
    "name": "Wuff",
    "type": "DOG",
    "comment": "This is a comment",
    "isAvailable": true
}
### get request for normal use
GET http://localhost:8080/animal

### GET request for for animal detailed view
GET http://localhost:8080/animal/999

### PATCH adopting a animal
PATCH http://localhost:8080/animal/4
Content-Type: application/json

{
  "adoptedBy": 1
}

### Adopted_by POST request
POST http://localhost:8080/animal
Content-Type: application/json

{
"name": "R",
"type": "DOG",
"comment": "This is a comment",
"isAvailable": true,
  "adoptedBy": {
    "name" : "Marius",
    "id" : 1
  }
}
