### adds an animal
POST http://localhost:8080/animal
Content-Type: application/json

{
    "name": "Wuff",
    "type": "DOG",
    "comment": "This is a comment",
    "isAvailable": true
}
### list all animals
GET http://localhost:8080/animal

### lists detailed view for a specific animal.
GET http://localhost:8080/animal/4

### Redirects to wiki page for a specific animal type
GET http://localhost:8080/animal/4/info

### PATCH adopting a animal
PATCH http://localhost:8080/animal/4
Content-Type: application/json

{
  "adoptedBy": 1
}

### Adopted_by POST request
POST http://localhost:8080/animal
Content-Type: application/json

{
"name": "R",
"type": "DOG",
"comment": "This is a comment",
"isAvailable": true,
  "adoptedBy": {
    "name" : "Marius",
    "id" : 1
  }
}
